version: '3.9'
services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - 5432:5432
    networks:
      - custom-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    restart: always
    depends_on: 
      - postgres_db
    networks:
      - custom-network
    command: >
      sh -c "npm run db:deploy && node dist/main.js"
    environment:
      DATABASE_URL: postgresql://postgres:prisma@postgres_db:5432/postgres?schema=public
      BASE_URL: http://localhost
    ports:
      - 3333:3333

  
networks:
  custom-network:
    name: custom-network

volumes:
  postgres_data: